CREATE DATABASE IF NOT EXISTS UserData;

USE UserData;

CREATE TABLE IF NOT EXISTS Users
(
    email        VARCHAR(200) NOT NULL UNIQUE,
    id           CHAR(36)     NOT NULL DEFAULT (UUID()),
    passwordHash VARCHAR(80)  NOT NULL,
    firstName    VARCHAR(200) NOT NULL,
    lastName     VARCHAR(200) NOT NULL,
    notes        TEXT,
    createdAt    DATETIME              DEFAULT NOW() NOT NULL,
    PRIMARY KEY (email, id)
);

INSERT INTO Users (email, passwordHash, firstName, lastName)
VALUES 
  ('user1@example.com', 'hash1', 'User', 'One'),
  ('user2@example.com', 'hash2', 'User', 'Two'),
  ('user3@example.com', 'hash3', 'User', 'Three'),
  ('user4@example.com', 'hash4', 'User', 'Four'),
  ('user5@example.com', 'hash5', 'User', 'Five'),
  ('user6@example.com', 'hash6', 'User', 'Six'),
  ('user7@example.com', 'hash7', 'User', 'Seven'),
  ('user8@example.com', 'hash8', 'User', 'Eight'),
  ('user9@example.com', 'hash9', 'User', 'Nine'),
  ('user10@example.com', 'hash10', 'User', 'Ten'),
  ('user11@example.com', 'hash11', 'User', 'Eleven'),
  ('user12@example.com', 'hash12', 'User', 'Twelve'),
  ('user13@example.com', 'hash13', 'User', 'Thirteen'),
  ('user14@example.com', 'hash14', 'User', 'Fourteen'),
  ('user15@example.com', 'hash15', 'User', 'Fifteen'),
  ('user16@example.com', 'hash16', 'User', 'Sixteen'),
  ('user17@example.com', 'hash17', 'User', 'Seventeen'),
  ('user18@example.com', 'hash18', 'User', 'Eighteen'),
  ('user19@example.com', 'hash19', 'User', 'Nineteen'),
  ('user20@example.com', 'hash20', 'User', 'Twenty'),
  ('user21@example.com', 'hash21', 'User', 'Twenty-One'),
  ('user22@example.com', 'hash22', 'User', 'Twenty-Two'),
  ('user23@example.com', 'hash23', 'User', 'Twenty-Three'),
  ('user24@example.com', 'hash24', 'User', 'Twenty-Four'),
  ('user25@example.com', 'hash25', 'User', 'Twenty-Five'),
  ('user26@example.com', 'hash26', 'User', 'Twenty-Six'),
  ('user27@example.com', 'hash27', 'User', 'Twenty-Seven'),
  ('user28@example.com', 'hash28', 'User', 'Twenty-Eight'),
  ('user29@example.com', 'hash29', 'User', 'Twenty-Nine'),
  ('user30@example.com', 'hash30', 'User', 'Thirty'),
  ('user31@example.com', 'hash31', 'User', 'Thirty-One'),
  ('user32@example.com', 'hash32', 'User', 'Thirty-Two'),
  ('user33@example.com', 'hash33', 'User', 'Thirty-Three'),
  ('user34@example.com', 'hash34', 'User', 'Thirty-Four'),
  ('user35@example.com', 'hash35', 'User', 'Thirty-Five'),
  ('user36@example.com', 'hash36', 'User', 'Thirty-Six'),
  ('user37@example.com', 'hash37', 'User', 'Thirty-Seven'),
  ('user38@example.com', 'hash38', 'User', 'Thirty-Eight'),
  ('user39@example.com', 'hash39', 'User', 'Thirty-Nine'),
  ('user40@example.com', 'hash40', 'User', 'Forty'),
  ('user41@example.com', 'hash41', 'User', 'Forty-One'),
  ('user42@example.com', 'hash42', 'User', 'Forty-Two'),
  ('user43@example.com', 'hash43', 'User', 'Forty-Three'),
  ('user44@example.com', 'hash44', 'User', 'Forty-Four'),
  ('user45@example.com', 'hash45', 'User', 'Forty-Five'),
  ('user46@example.com', 'hash46', 'User', 'Forty-Six'),
  ('user47@example.com', 'hash47', 'User', 'Forty-Seven'),
  ('user48@example.com', 'hash48', 'User', 'Forty-Eight'),
  ('user49@example.com', 'hash49', 'User', 'Forty-Nine'),
  ('user50@example.com', 'hash50', 'User', 'Fifty');
