version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserData
    ports:
      - 3306:3306
    volumes:
      - ./misc/init.sql:/docker-entrypoint-initdb.d/init.sql
